<?xml version="1.0"?>
<package format="2">
  <name>look_up</name>
  <version>0.1.0</version>
  <description>A package for multi-drone YOLO-based human tracking with a central lookup service.</description>

  <maintainer email="qing199822@users.noreply.github.com">ZZU FLY Team</maintainer>
  <license>LicenseRef-Team-Code</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>darknet_ros_msgs</depend>
  <depend>topic_tools</depend>
  
  <build_depend>message_generation</build_depend>
  <exec_depend>competition_compliance</exec_depend>
  <exec_depend>message_runtime</exec_depend>

</package>
