<?xml version="1.0"?>
<package format="2">
  <name>transform_tree</name>
  <version>0.1.0</version>
  <description>A package to broadcast TF transforms from odometry messages manually into a /tf topic.</description>

  <!-- 维护者信息 -->
  <maintainer email="qing199822@users.noreply.github.com">ZZU FLY Team</maintainer>

  <!-- 许可证信息 -->
  <license>LicenseRef-Team-Code</license>

  <!-- 
    构建工具依赖，对于catkin包，这总是catkin
  -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- 
    构建依赖: 编译代码时需要的包。
    使用 <depend> 标签同时指定了构建、执行和测试依赖，对于这些核心包是合适的。
  -->
  <depend>roscpp</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_msgs</depend>
  
  <!-- 
    <build_depend> 编译时依赖
    <build_export_depend> 导出给依赖此包的编译依赖
    <exec_depend> 运行时依赖
    <test_depend> 测试时依赖
    对于roscpp, nav_msgs等，它们在编译和运行时都需要，所以用<depend>更简洁。
  -->

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->
  </export>
</package>
